OpenSAMLAndExamples: cc.saml.SAMLSignature Class Reference
cc.saml.SAMLSignature Class Reference
Classes
class KeyValueKeySelector
class SimpleKeySelectorResult
Public Member Functions
SAMLSignature ()
void signSAMLObject (Element target) throws GeneralSecurityException, XMLSignatureException, MarshalException
boolean verifySAMLSignature (Element target) throws Exception
void writeFiles (Document doc, String baseFilename) throws IOException
Static Public Member Functions
static void main (String[] args) throws Exception
Static Package Functions
static boolean algEquals (String algURI, String algName)
Private Attributes
XMLSignatureFactory factory
KeyStore keyStore
KeyPair keyPair
KeyInfo keyInfo
Detailed Description
Utility for signing SAML DOM objects (assertions, requests, and responses) and for validating and checking signatures on SAML DOM objects. Unlike the rest of this package, this utility does not rely on OpenSAML; it operates directly on DOM trees. (There is an import of OpenSAML's XMLObject type, but that's just for our main method, which in turn is just for testing purposes.)
Author
Will Provost
Definition at line 80 of file SAMLSignature.java.
Constructor & Destructor Documentation
cc.saml.SAMLSignature.SAMLSignature ()
Loads a keystore and builds a stock key-info structure for use by base classes.
Definition at line 154 of file SAMLSignature.java.
References cc.security.KeyStoreUtil.getKeyStore().
Referenced by cc.saml.SAMLSignature.main().
Member Function Documentation
static boolean cc.saml.SAMLSignature.algEquals (String algURI, String algName) static package
Test that a formal URI expresses the same algorithm as a conventional short name such as "DSA" or "RSA".
Definition at line 350 of file SAMLSignature.java.
Referenced by cc.saml.SAMLSignature.KeyValueKeySelector.select().
static void cc.saml.SAMLSignature.main (String[] args) throws Exception static
Parse the command line for a filename to read, and optionally a filename to write (absent which the application will write to the console). Reads the given file as an XMLObject, signs it using the configured key, and then dumps using a simple pretty printer. Or, validates the signature found in the given file.
Definition at line 94 of file SAMLSignature.java.
References cc.saml.SAMLSignature.SAMLSignature(), cc.saml.SAMLSignature.signSAMLObject(), cc.saml.SAMLSignature.verifySAMLSignature(), and cc.saml.SAMLSignature.writeFiles().
void cc.saml.SAMLSignature.signSAMLObject (Element target) throws GeneralSecurityException, XMLSignatureException, MarshalException
Adds an enveloped signature to the given element. Then moves the signature element so that it is in the correct position according to the SAML assertion and protocol schema: it must immediately follow any Issuer and precede everything else.
Definition at line 195 of file SAMLSignature.java.
Referenced by cc.saml.SAMLSignature.main().
boolean cc.saml.SAMLSignature.verifySAMLSignature (Element target) throws Exception
Seeks out the signature element in the given tree, and validates it. Searches the configured keystore (asking it to function also as a truststore) for a certificate with a matching fingerprint.
Returns
true if the signature validates and we know the signer; false otherwise
Definition at line 260 of file SAMLSignature.java.
References cc.security.KeyStoreUtil.getAliases(), and cc.security.KeyStoreUtil.getCertificate().
Referenced by cc.saml.SAMLSignature.main().
void cc.saml.SAMLSignature.writeFiles (Document doc, String baseFilename) throws IOException
Helper method to write two output files from a given DOM tree: one is the raw output and one is pretty-printed and given the suffix "_pretty" before the ".xml" extension.
Definition at line 383 of file SAMLSignature.java.
References cc.xml.PrettyPrinter.prettyPrint().
Referenced by cc.saml.SAMLSignature.main().
Member Data Documentation
XMLSignatureFactory cc.saml.SAMLSignature.factory private
Definition at line 82 of file SAMLSignature.java.
KeyInfo cc.saml.SAMLSignature.keyInfo private
Definition at line 85 of file SAMLSignature.java.
KeyPair cc.saml.SAMLSignature.keyPair private
Definition at line 84 of file SAMLSignature.java.
KeyStore cc.saml.SAMLSignature.keyStore private
Definition at line 83 of file SAMLSignature.java.
The documentation for this class was generated from the following file:
OpenSAML/src/cc/saml/SAMLSignature.java