OpenSAMLAndExamples: cc.xml.PrettyPrinter Class Reference
cc.xml.PrettyPrinter Class Reference
Classes
class StreamAdapter
Public Member Functions
String toString ()
void startDocument () throws SAXException
void endDocument () throws SAXException
void startElement (String URI, String name, String qName, Attributes attributes) throws SAXException
void endElement (String URI, String name, String qName) throws SAXException
void characters (char[] chars, int start, int length) throws SAXException
Static Public Member Functions
static String prettyPrint (byte[] content)
static String prettyPrint (String content)
static String prettyPrint (InputStream content)
static String prettyPrint (Document doc) throws TransformerException
Static Private Member Functions
static String escape (char[] chars, int start, int length)
Private Attributes
String indent = ""
StringBuffer currentValue = null
StringBuffer output = new StringBuffer ()
boolean justHitStartTag
Static Private Attributes
static final String standardIndent = " "
static final String endLine
Detailed Description
This class "pretty prints" an XML stream to something more human-readable. It duplicates the character content with some modifications to whitespace, restoring line breaks and a simple pattern of indenting child elements.
This version of the class acts as a SAX 2.0 DefaultHandler, so to provide the unformatted XML just pass a new instance to a SAX parser. Its output is via the toString method.
One major limitation: we gather character data for elements in a single buffer, so mixed-content documents will lose a lot of data! This works best with data-centric documents where elements either have single values or child elements, but not both.
Author
Will Provost
Definition at line 35 of file PrettyPrinter.java.
Member Function Documentation
void cc.xml.PrettyPrinter.characters (char[] chars, int start, int length) throws SAXException
When the currentValue buffer is enabled, appends character data into it, to be gathered when the element end tag is encountered.
Definition at line 251 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.currentValue, and cc.xml.PrettyPrinter.escape().
void cc.xml.PrettyPrinter.endDocument () throws SAXException
Prints a blank line at the end of the reformatted document.
Definition at line 177 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.endLine, and cc.xml.PrettyPrinter.output.
void cc.xml.PrettyPrinter.endElement (String URI, String name, String qName) throws SAXException
Checks the currentValue buffer to gather element content. Writes this out if it is available. Writes the element end tag.
Definition at line 222 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.currentValue, cc.xml.PrettyPrinter.endLine, cc.xml.PrettyPrinter.indent, cc.xml.PrettyPrinter.justHitStartTag, cc.xml.PrettyPrinter.output, and cc.xml.PrettyPrinter.standardIndent.
static String cc.xml.PrettyPrinter.escape (char[] chars, int start, int length) static private
Filter to pass strings to output, escaping < and & characters to &lt; and &amp; respectively.
Definition at line 262 of file PrettyPrinter.java.
Referenced by cc.xml.PrettyPrinter.characters().
static String cc.xml.PrettyPrinter.prettyPrint (byte[] content) static
Convenience method to wrap pretty-printing SAX pass over existing content.
Definition at line 41 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.toString().
Referenced by cc.xml.PrettyPrinter.StreamAdapter.flushPretty(), cc.xml.PrettyPrinter.prettyPrint(), and cc.saml.SAMLSignature.writeFiles().
static String cc.xml.PrettyPrinter.prettyPrint (String content) static
Convenience method to wrap pretty-printing SAX pass over existing content.
Definition at line 64 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.toString().
static String cc.xml.PrettyPrinter.prettyPrint (InputStream content) static
Convenience method to wrap pretty-printing SAX pass over existing content.
Definition at line 86 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.toString().
static String cc.xml.PrettyPrinter.prettyPrint (Document doc) throws TransformerException static
Convenience method to wrap pretty-printing SAX pass over existing content.
Definition at line 108 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.prettyPrint().
void cc.xml.PrettyPrinter.startDocument () throws SAXException
Prints the XML declaration.
Definition at line 167 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.endLine, and cc.xml.PrettyPrinter.output.
void cc.xml.PrettyPrinter.startElement (String URI, String name, String qName, Attributes attributes) throws SAXException
Writes the start tag for the element. Attributes are written out, one to a text line. Starts gathering character data for the element.
Definition at line 188 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.currentValue, cc.xml.PrettyPrinter.endLine, cc.xml.PrettyPrinter.indent, cc.xml.PrettyPrinter.justHitStartTag, cc.xml.PrettyPrinter.output, and cc.xml.PrettyPrinter.standardIndent.
String cc.xml.PrettyPrinter.toString ()
Call this to get the formatted XML post-parsing.
Definition at line 159 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.output.
Referenced by cc.xml.PrettyPrinter.prettyPrint().
Member Data Documentation
StringBuffer cc.xml.PrettyPrinter.currentValue = null private
A buffer for character data. It is "enabled" in startElement by being initialized to a new StringBuffer, and then read and reset to null in endElement.
Definition at line 288 of file PrettyPrinter.java.
Referenced by cc.xml.PrettyPrinter.characters(), cc.xml.PrettyPrinter.endElement(), and cc.xml.PrettyPrinter.startElement().
final String cc.xml.PrettyPrinter.endLine static private
Initial value:
=
        System.getProperty ("line.separator")
Definition at line 298 of file PrettyPrinter.java.
Referenced by cc.xml.PrettyPrinter.endDocument(), cc.xml.PrettyPrinter.endElement(), cc.xml.PrettyPrinter.startDocument(), and cc.xml.PrettyPrinter.startElement().
String cc.xml.PrettyPrinter.indent = "" private
This whitespace string is expanded and collapsed to manage the output indenting.
Definition at line 280 of file PrettyPrinter.java.
Referenced by cc.xml.PrettyPrinter.endElement(), and cc.xml.PrettyPrinter.startElement().
boolean cc.xml.PrettyPrinter.justHitStartTag private
Definition at line 295 of file PrettyPrinter.java.
Referenced by cc.xml.PrettyPrinter.endElement(), and cc.xml.PrettyPrinter.startElement().
StringBuffer cc.xml.PrettyPrinter.output = new StringBuffer () private
The primary buffer for accumulating the formatted XML.
Definition at line 293 of file PrettyPrinter.java.
Referenced by cc.xml.PrettyPrinter.endDocument(), cc.xml.PrettyPrinter.endElement(), cc.xml.PrettyPrinter.startDocument(), cc.xml.PrettyPrinter.startElement(), and cc.xml.PrettyPrinter.toString().
final String cc.xml.PrettyPrinter.standardIndent = " " static private
Definition at line 297 of file PrettyPrinter.java.
Referenced by cc.xml.PrettyPrinter.endElement(), and cc.xml.PrettyPrinter.startElement().
The documentation for this class was generated from the following file:
OpenSAML/src/cc/xml/PrettyPrinter.java