OpenSAMLAndExamples: cc.saml.SAMLBinding Class Reference
cc.saml.SAMLBinding Class Reference
Public Member Functions
void wrapAndPrintToFile (XMLObject object, String filename) throws IOException, MarshallingException, TransformerException
void wrapAndPrintResponse (Assertion assertion, String filename) throws IOException, MarshallingException, TransformerException
Public Member Functions inherited from cc.saml.SAMLProtocol
void printResponse (Assertion assertion, String filename) throws IOException, MarshallingException, TransformerException
AuthnQuery createStockAuthnQuery () throws Exception
AttributeQuery createStockAttributeQuery () throws Exception
AuthzDecisionQuery createStockAuthzDecisionQuery () throws Exception
Public Member Functions inherited from cc.saml.SAMLAssertion
Assertion createStockAuthnAssertion () throws Exception
void readAuthnAssertion (String filename) throws Exception
Assertion createStockAttributeAssertion () throws Exception
void readAttributeAssertion (String filename) throws Exception
Assertion createStockAuthzDecisionAssertion () throws Exception
void readAuthzDecisionAssertion (String filename) throws Exception
Public Member Functions inherited from cc.saml.SAML
SAML ()
SAML (String issuerURL)
Static Public Member Functions
static void main (String[] args) throws Exception
Static Public Member Functions inherited from cc.saml.SAMLProtocol
static void main (String[] args) throws Exception
Static Public Member Functions inherited from cc.saml.SAMLAssertion
static void main (String[] args) throws Exception
Static Public Member Functions inherited from cc.saml.SAML
static void main (String[] args) throws Exception
Static Private Member Functions
static void die ()
Static Private Attributes
static final String REQUEST_SUFFIX = "Request.xml"
static final String RESPONSE_SUFFIX = "Response.xml"
Additional Inherited Members
Static Package Functions inherited from cc.saml.SAML
[static initializer]
Detailed Description
Simple examples of coding to the OpenSAML API. Methods here can read and write SAML assertions, queries, and responses using bindings including SOAP 1.1 over HTTP. (Nothing in this class performs any actual HTTP messaging, however: we continue to represent I/O using files and console streams.)
Author
Will Provost
Definition at line 30 of file SAMLBinding.java.
Member Function Documentation
static void cc.saml.SAMLBinding.die () static private
Definition at line 36 of file SAMLBinding.java.
Referenced by cc.saml.SAMLBinding.main().
static void cc.saml.SAMLBinding.main (String[] args) throws Exception static
Parses the command line for instructions to write a SAML request or response in one of the three main types, and for a base filename. The command methods will automatically append either "Request.xml" or "Response.xml" to the base name. The file content in each case will be a SOAP Envelope, wrapping the request or response as the message body according to the SAML 2.0 SOAP binding.
Definition at line 52 of file SAMLBinding.java.
References cc.saml.SAMLAssertion.createStockAttributeAssertion(), cc.saml.SAMLProtocol.createStockAttributeQuery(), cc.saml.SAMLAssertion.createStockAuthnAssertion(), cc.saml.SAMLProtocol.createStockAuthnQuery(), cc.saml.SAMLAssertion.createStockAuthzDecisionAssertion(), cc.saml.SAMLProtocol.createStockAuthzDecisionQuery(), cc.saml.SAMLBinding.die(), cc.saml.SAMLBinding.wrapAndPrintResponse(), and cc.saml.SAMLBinding.wrapAndPrintToFile().
void cc.saml.SAMLBinding.wrapAndPrintResponse (Assertion assertion, String filename) throws IOException, MarshallingException, TransformerException
Helper method to generate and pretty-print a SOAP response envelope, based on a given request envelope (for our inResponseTo value) and a pre-built assertion.
Definition at line 113 of file SAMLBinding.java.
References cc.saml.SAMLBinding.wrapAndPrintToFile().
Referenced by cc.saml.SAMLBinding.main().
void cc.saml.SAMLBinding.wrapAndPrintToFile (XMLObject object, String filename) throws IOException, MarshallingException, TransformerException
Helper method to generate and pretty-print a SOAP envelope, based on an XML object and a filename.
Definition at line 96 of file SAMLBinding.java.
Referenced by cc.saml.SAMLBinding.main(), and cc.saml.SAMLBinding.wrapAndPrintResponse().
Member Data Documentation
final String cc.saml.SAMLBinding.REQUEST_SUFFIX = "Request.xml" static private
Definition at line 33 of file SAMLBinding.java.
final String cc.saml.SAMLBinding.RESPONSE_SUFFIX = "Response.xml" static private
Definition at line 34 of file SAMLBinding.java.
The documentation for this class was generated from the following file:
OpenSAML/src/cc/saml/SAMLBinding.java