OpenSAMLAndExamples: cc.xml.PrettyPrinter.StreamAdapter Class Reference
cc.xml.PrettyPrinter.StreamAdapter Class Reference
Public Member Functions
StreamAdapter (Writer finalDestination)
void write (int b)
void flushPretty () throws IOException
Package Attributes
Writer finalDestination
Private Attributes
ByteArrayOutputStream out = new ByteArrayOutputStream ()
Detailed Description
Definition at line 129 of file PrettyPrinter.java.
Constructor & Destructor Documentation
cc.xml.PrettyPrinter.StreamAdapter.StreamAdapter (Writer finalDestination)
Definition at line 132 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.StreamAdapter.finalDestination.
Member Function Documentation
void cc.xml.PrettyPrinter.StreamAdapter.flushPretty () throws IOException
Definition at line 142 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.StreamAdapter.finalDestination, cc.xml.PrettyPrinter.StreamAdapter.out, and cc.xml.PrettyPrinter.prettyPrint().
void cc.xml.PrettyPrinter.StreamAdapter.write (int b)
Definition at line 137 of file PrettyPrinter.java.
References cc.xml.PrettyPrinter.StreamAdapter.out.
Member Data Documentation
Writer cc.xml.PrettyPrinter.StreamAdapter.finalDestination package
Definition at line 153 of file PrettyPrinter.java.
Referenced by cc.xml.PrettyPrinter.StreamAdapter.flushPretty(), and cc.xml.PrettyPrinter.StreamAdapter.StreamAdapter().
ByteArrayOutputStream cc.xml.PrettyPrinter.StreamAdapter.out = new ByteArrayOutputStream () private
Definition at line 152 of file PrettyPrinter.java.
Referenced by cc.xml.PrettyPrinter.StreamAdapter.flushPretty(), and cc.xml.PrettyPrinter.StreamAdapter.write().
The documentation for this class was generated from the following file:
OpenSAML/src/cc/xml/PrettyPrinter.java