OpenSAMLAndExamples: cc.saml.SAMLProtocol Class Reference
cc.saml.SAMLProtocol Class Reference
Public Member Functions
void printResponse (Assertion assertion, String filename) throws IOException, MarshallingException, TransformerException
AuthnQuery createStockAuthnQuery () throws Exception
AttributeQuery createStockAttributeQuery () throws Exception
AuthzDecisionQuery createStockAuthzDecisionQuery () throws Exception
Public Member Functions inherited from cc.saml.SAMLAssertion
Assertion createStockAuthnAssertion () throws Exception
void readAuthnAssertion (String filename) throws Exception
Assertion createStockAttributeAssertion () throws Exception
void readAttributeAssertion (String filename) throws Exception
Assertion createStockAuthzDecisionAssertion () throws Exception
void readAuthzDecisionAssertion (String filename) throws Exception
Public Member Functions inherited from cc.saml.SAML
SAML ()
SAML (String issuerURL)
Static Public Member Functions
static void main (String[] args) throws Exception
Static Public Member Functions inherited from cc.saml.SAMLAssertion
static void main (String[] args) throws Exception
Static Public Member Functions inherited from cc.saml.SAML
static void main (String[] args) throws Exception
Static Private Member Functions
static void die ()
Static Private Attributes
static final String QUERY_SUFFIX = "Query.xml"
static final String RESPONSE_SUFFIX = "Response.xml"
Additional Inherited Members
Static Package Functions inherited from cc.saml.SAML
[static initializer]
Detailed Description
Simple examples of coding to the OpenSAML API. Methods here can write SAMLP queries and responses for each of the three main types: authentication, authorization decision, and attributes.
Author
Will Provost
Definition at line 40 of file SAMLProtocol.java.
Member Function Documentation
AttributeQuery cc.saml.SAMLProtocol.createStockAttributeQuery () throws Exception
Creates a file whose contents are a SAML attribute query.
Definition at line 169 of file SAMLProtocol.java.
Referenced by cc.saml.SAMLBinding.main(), and cc.saml.SAMLProtocol.main().
AuthnQuery cc.saml.SAMLProtocol.createStockAuthnQuery () throws Exception
Creates a file whose contents are a SAML authentication query.
Definition at line 133 of file SAMLProtocol.java.
Referenced by cc.saml.SAMLBinding.main(), and cc.saml.SAMLProtocol.main().
AuthzDecisionQuery cc.saml.SAMLProtocol.createStockAuthzDecisionQuery () throws Exception
Creates a file whose contents are a SAML authorization-decision query.
Definition at line 205 of file SAMLProtocol.java.
Referenced by cc.saml.SAMLBinding.main(), and cc.saml.SAMLProtocol.main().
static void cc.saml.SAMLProtocol.die () static private
Definition at line 46 of file SAMLProtocol.java.
Referenced by cc.saml.SAMLProtocol.main().
static void cc.saml.SAMLProtocol.main (String[] args) throws Exception static
Parses the command line for instructions to write a SAML query or response in one of the three main types, and for a base filename. The command methods will automatically append either "Query.xml" or "Response.xml" to the base name.
Definition at line 60 of file SAMLProtocol.java.
References cc.saml.SAMLAssertion.createStockAttributeAssertion(), cc.saml.SAMLProtocol.createStockAttributeQuery(), cc.saml.SAMLAssertion.createStockAuthnAssertion(), cc.saml.SAMLProtocol.createStockAuthnQuery(), cc.saml.SAMLAssertion.createStockAuthzDecisionAssertion(), cc.saml.SAMLProtocol.createStockAuthzDecisionQuery(), cc.saml.SAMLProtocol.die(), and cc.saml.SAMLProtocol.printResponse().
void cc.saml.SAMLProtocol.printResponse (Assertion assertion, String filename) throws IOException, MarshallingException, TransformerException
Helper method to generate and pretty-print a response, based on a given query (for our inResponseTo value) and an assertion.
Definition at line 104 of file SAMLProtocol.java.
Referenced by cc.saml.SAMLProtocol.main().
Member Data Documentation
final String cc.saml.SAMLProtocol.QUERY_SUFFIX = "Query.xml" static private
Definition at line 43 of file SAMLProtocol.java.
final String cc.saml.SAMLProtocol.RESPONSE_SUFFIX = "Response.xml" static private
Definition at line 44 of file SAMLProtocol.java.
The documentation for this class was generated from the following file:
OpenSAML/src/cc/saml/SAMLProtocol.java