OpenSAMLAndExamples: cc.security.KeyStoreUtil Class Reference
cc.security.KeyStoreUtil Class Reference
Static Public Member Functions
static KeyStore getKeyStore (String filename, String password) throws KeyStoreException
static KeyStore getKeyStore (InputStream in, String password) throws KeyStoreException
static List getAliases (KeyStore keystore) throws KeyStoreException
static Key getKey (KeyStore keystore, String alias, String password) throws GeneralSecurityException
static
java.security.cert.Certificate getCertificate (KeyStore keystore, String alias) throws GeneralSecurityException
static String spillBeans (Key key)
static String spillBeans (java.security.cert.Certificate cert) throws GeneralSecurityException
static String getUserInput (String prompt) throws IOException
static void appendHexValue (StringBuffer buffer, byte b)
static void appendHexValue (StringBuffer buffer, byte[] bytes)
static void main (String[] args) throws Exception
Static Private Attributes
static final String endLine
Detailed Description
Simple utility for managing common KeyStore tasks.
Author
Will Provost
Definition at line 16 of file KeyStoreUtil.java.
Member Function Documentation
static void cc.security.KeyStoreUtil.appendHexValue (StringBuffer buffer, byte b) static
Helper method that converts a single byte to a hex string representation.
Parameters
b byte Byte to convert
Returns
StringBuffer with the two-digit hex string
Definition at line 140 of file KeyStoreUtil.java.
Referenced by cc.security.KeyStoreUtil.appendHexValue(), and cc.security.KeyStoreUtil.spillBeans().
static void cc.security.KeyStoreUtil.appendHexValue (StringBuffer buffer, byte[] bytes) static
Helper that appends a hex representation of a byte array to an existing StringBuffer.
Definition at line 154 of file KeyStoreUtil.java.
References cc.security.KeyStoreUtil.appendHexValue().
static List cc.security.KeyStoreUtil.getAliases (KeyStore keystore) throws KeyStoreException static
List all the key and certificate aliases in the keystore.
Returns
A list of Strings
Definition at line 67 of file KeyStoreUtil.java.
Referenced by cc.security.KeyStoreUtil.main(), and cc.saml.SAMLSignature.verifySAMLSignature().
static java.security.cert.Certificate cc.security.KeyStoreUtil.getCertificate (KeyStore keystore, String alias) throws GeneralSecurityException static
Get a certificate from the keystore by name.
Definition at line 86 of file KeyStoreUtil.java.
Referenced by cc.security.KeyStoreUtil.main(), and cc.saml.SAMLSignature.verifySAMLSignature().
static Key cc.security.KeyStoreUtil.getKey (KeyStore keystore, String alias, String password) throws GeneralSecurityException static
Get a private key from the keystore by name and password.
Definition at line 76 of file KeyStoreUtil.java.
Referenced by cc.security.KeyStoreUtil.main().
static KeyStore cc.security.KeyStoreUtil.getKeyStore (String filename, String password) throws KeyStoreException static
Get a KeyStore object given the keystore filename and password.
Definition at line 21 of file KeyStoreUtil.java.
Referenced by cc.security.KeyStoreUtil.main(), and cc.saml.SAMLSignature.SAMLSignature().
static KeyStore cc.security.KeyStoreUtil.getKeyStore (InputStream in, String password) throws KeyStoreException static
Get a KeyStore object given the keystore filename and password.
Definition at line 44 of file KeyStoreUtil.java.
static String cc.security.KeyStoreUtil.getUserInput (String prompt) throws IOException static
Helper method to solicit a line of user input from the console.
Definition at line 123 of file KeyStoreUtil.java.
Referenced by cc.security.KeyStoreUtil.main().
static void cc.security.KeyStoreUtil.main (String[] args) throws Exception static
As an application, this class will operate something like the keytool -list command: it will read out every alias in the keystore, and with the user's provided password for a given key will write out all data on the key and/or certificate.
Definition at line 169 of file KeyStoreUtil.java.
References cc.security.KeyStoreUtil.getAliases(), cc.security.KeyStoreUtil.getCertificate(), cc.security.KeyStoreUtil.getKey(), cc.security.KeyStoreUtil.getKeyStore(), cc.security.KeyStoreUtil.getUserInput(), and cc.security.KeyStoreUtil.spillBeans().
static String cc.security.KeyStoreUtil.spillBeans (Key key) static
Dump all data about the private key to the console.
Definition at line 95 of file KeyStoreUtil.java.
References cc.security.KeyStoreUtil.appendHexValue(), and cc.security.KeyStoreUtil.endLine.
Referenced by cc.security.KeyStoreUtil.main().
static String cc.security.KeyStoreUtil.spillBeans (java.security.cert.Certificate cert) throws GeneralSecurityException static
Dump all data about the certificate to the console.
Definition at line 109 of file KeyStoreUtil.java.
References cc.security.KeyStoreUtil.appendHexValue(), and cc.security.KeyStoreUtil.endLine.
Member Data Documentation
final String cc.security.KeyStoreUtil.endLine static private
Initial value:
=
        System.getProperty ("line.separator")
Definition at line 160 of file KeyStoreUtil.java.
Referenced by cc.security.KeyStoreUtil.spillBeans().
The documentation for this class was generated from the following file:
OpenSAML/src/cc/security/KeyStoreUtil.java