OpenSAMLAndExamples: cc.saml.SAMLAssertion Class Reference
cc.saml.SAMLAssertion Class Reference
Public Member Functions
Assertion createStockAuthnAssertion () throws Exception
void readAuthnAssertion (String filename) throws Exception
Assertion createStockAttributeAssertion () throws Exception
void readAttributeAssertion (String filename) throws Exception
Assertion createStockAuthzDecisionAssertion () throws Exception
void readAuthzDecisionAssertion (String filename) throws Exception
Public Member Functions inherited from cc.saml.SAML
SAML ()
SAML (String issuerURL)
Static Public Member Functions
static void main (String[] args) throws Exception
Static Public Member Functions inherited from cc.saml.SAML
static void main (String[] args) throws Exception
Static Private Member Functions
static void die ()
Additional Inherited Members
Static Package Functions inherited from cc.saml.SAML
[static initializer]
Detailed Description
Simple examples of coding to the OpenSAML API. Methods here can write and parse each of the three main assertion types: authentication, authorization decision, and attributes.
Author
Will Provost
Definition at line 40 of file SAMLAssertion.java.
Member Function Documentation
Assertion cc.saml.SAMLAssertion.createStockAttributeAssertion () throws Exception
Creates a file whose contents are a SAML attribute assertion.
Definition at line 171 of file SAMLAssertion.java.
References cc.saml.SAML.builder.
Referenced by cc.saml.SAMLBinding.main(), cc.saml.SAMLAssertion.main(), and cc.saml.SAMLProtocol.main().
Assertion cc.saml.SAMLAssertion.createStockAuthnAssertion () throws Exception
Creates a file whose contents are a SAML authentication assertion.
Definition at line 95 of file SAMLAssertion.java.
Referenced by cc.saml.SAMLBinding.main(), cc.saml.SAMLAssertion.main(), and cc.saml.SAMLProtocol.main().
Assertion cc.saml.SAMLAssertion.createStockAuthzDecisionAssertion () throws Exception
Creates a file whose contents are a SAML authorization-decision assertion.
Definition at line 262 of file SAMLAssertion.java.
Referenced by cc.saml.SAMLBinding.main(), cc.saml.SAMLAssertion.main(), and cc.saml.SAMLProtocol.main().
static void cc.saml.SAMLAssertion.die () static private
Definition at line 43 of file SAMLAssertion.java.
Referenced by cc.saml.SAMLAssertion.main().
static void cc.saml.SAMLAssertion.main (String[] args) throws Exception static
Parse the command line for instructions to write or read one of the three types of assertions and for a target filename. Dispatch to one of the six command methods on this class.
Definition at line 55 of file SAMLAssertion.java.
References cc.saml.SAMLAssertion.createStockAttributeAssertion(), cc.saml.SAMLAssertion.createStockAuthnAssertion(), cc.saml.SAMLAssertion.createStockAuthzDecisionAssertion(), cc.saml.SAMLAssertion.die(), cc.saml.SAMLAssertion.readAttributeAssertion(), cc.saml.SAMLAssertion.readAuthnAssertion(), and cc.saml.SAMLAssertion.readAuthzDecisionAssertion().
void cc.saml.SAMLAssertion.readAttributeAssertion (String filename) throws Exception
Parses a SAML attribute assertion as found in a file, and prints out all attributes.
Definition at line 233 of file SAMLAssertion.java.
Referenced by cc.saml.SAMLAssertion.main().
void cc.saml.SAMLAssertion.readAuthnAssertion (String filename) throws Exception
Parses a SAML authentication assertion as found in a file, and prints out information about issuer, subject, and authentication context.
Definition at line 149 of file SAMLAssertion.java.
Referenced by cc.saml.SAMLAssertion.main().
void cc.saml.SAMLAssertion.readAuthzDecisionAssertion (String filename) throws Exception
Parses a SAML authorization-decision assertion as found in a file, and prints out the essential information.
Definition at line 307 of file SAMLAssertion.java.
Referenced by cc.saml.SAMLAssertion.main().
The documentation for this class was generated from the following file:
OpenSAML/src/cc/saml/SAMLAssertion.java